import Head from "next/head";
import Navbar from '../Components/Navbar' 
function about() {
  return (
    <div>
      <Head>
        <title>La Laundry</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar navLogo='/img/laundry-logo.png'  />
      <div>

        <p className="text-5xl text-center">This is About</p>
      </div>
    </div>
  );
}

export default about;


