


import Head from 'next/head';
// import ContactComp from '../components/ContactComp'
import Footer from '../components/Footer';

import Navbar from '../components/Navbar'
type Props = {}

function contact({}: Props) {
  return (
    <div>
      <Head>
          <title>La Laundry - Contact</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/img/laundry-logo-white-small.png" />

        </Head>

      <Navbar navLogo='/img/Lalundry-logo-white.png'  headerBGColor="transparent" headerTextColor="white" />
        



        {/* <ContactComp /> */}
        
        <Footer />
    </div>
  )
}

export default contact

